version: '3'

services:

  minio:
    image: minio/minio:latest
    # image: docker.singlewave.co.uk/minio-dev:latest
    ports:
      - "19000:9000"
      - "19001:9001"
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    command: server --console-address ":9001" /data{1...4}
    volumes:
      - ${MINIO_DATA_DIR}:/data