version: '3.6'

services:
  postgres:
    image: postgres:14
    ports:
      - "5414:5432"
    volumes:
      - "/A/data/storage/pgdata14:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
