version: '3'

services:
  pg10:
    image: postgres:10
    ports:
      - "5410:5432"
    volumes:
      - "/Users/gigio/data/storage/pgdata10:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}