version: '3.1'

services:
  sentry:
    image: saxix/sentry:9.1.2-5
    ports:
      - "${SENTRY_PORT:-9000}:9000"
      - "${SENTRY_PORT_8888:-8888}:8888"
      - "${SENTRY_PORT_15000:-15000}:15000"
    environment:
        SUPERVISOR_USER: superadmin
        SUPERVISOR_PWD: superadmin
        START_FLOWER: 0
        SENTRY_SECRET_KEY: ${SENTRY_SECRET_KEY}
        SENTRY_REDIS_HOST: redis
        SENTRY_POSTGRES_HOST: postgres
        SENTRY_EMAIL_USER: ${SENTRY_EMAIL_USER}
        SENTRY_EMAIL_USE_TLS: 1
        SENTRY_EMAIL_PORT: 587
        SENTRY_EMAIL_PASSWORD: ${SENTRY_EMAIL_PASSWORD}
        SENTRY_EMAIL_HOST: smtpd
        SENTRY_DB_USER: postgres
        SENTRY_DB_PASSWORD: ${POSTGRES_PASSWORD}
        SENTRY_DB_NAME: sentry
        SENTRY_ADMIN_USERNAME: admin
        SENTRY_ADMIN_PASSWORD: admin
        LOG_LEVEL: error
        FLOWER_ADMIN_USERNAME: admin
        CIRCUS_WEB: 0
        SENTRY_URL_PREFIX: http://localhost:9000
    depends_on:
      - postgres
      - redis
