version: '3.6'

services:
  postgres:
    image: postgres:${PG_VERSION}
    ports:
      - "54${PG_VERSION}:5432"
    volumes:
      - "${PG_ROOT_DATA_DIR}${PG_VERSION}:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
