version: '3'
# to activate : docker-compose up -d
services:

  postgres:
    image: postgres:${PG_VERSION}
    ports:
      - "5432:5432"
    volumes:
      - "${PG_DATA_DIR}:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  sentry:
    image: saxix/sentry:9.1.2-5
    ports:
      - "9000:9000"
      - "8888:8888"
      - "15000:15000"
    environment:
        SUPERVISOR_USER: superadmin
        SUPERVISOR_PWD: superadmin
        START_FLOWER: 0
        SENTRY_SECRET_KEY: ${SENTRY_SECRET_KEY}
        SENTRY_REDIS_HOST: redis
        SENTRY_POSTGRES_HOST: postgres
        SENTRY_EMAIL_USER: ${SENTRY_EMAIL_USER}
        SENTRY_EMAIL_USE_TLS: 1
        SENTRY_EMAIL_PORT: 587
        SENTRY_EMAIL_PASSWORD: ${SENTRY_EMAIL_PASSWORD}
        SENTRY_EMAIL_HOST: smtpd
        SENTRY_DB_USER: postgres
        SENTRY_DB_PASSWORD: ${POSTGRES_PASSWORD}
        SENTRY_DB_NAME: sentry
        SENTRY_ADMIN_USERNAME: admin
        SENTRY_ADMIN_PASSWORD: admin
        LOG_LEVEL: error
        FLOWER_ADMIN_USERNAME: admin
        CIRCUS_WEB: 0
        SENTRY_URL_PREFIX: http://localhost:9000
        
  redis:
      image: "redis:alpine"
      ports:
        - "6379:6379"

  sqs:
      image: "roribio16/alpine-sqs:latest"
      ports:
        - 9324:9324
        - 9325:9325

  minio:
    image: minio/minio:latest
    # image: docker.singlewave.co.uk/minio-dev:latest
    ports:
      - "19000:9000"
      - "19001:9001"
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    command: server --console-address :9001 /data{1...4}
