services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:${MSSQL_VERSION:-latest}
    user: root
    ports:
      - "${MSSQL_PORT:-1433}:1433"
    volumes: 
      - "${MSSQL_DATA_DIR}/data:/var/opt/mssql/data"
      - "${MSSQL_DATA_DIR}/log:/var/opt/mssql/log"
      - "${MSSQL_DATA_DIR}/secrets:/var/opt/mssql/secrets"
      - "${MSSQL_DATA_DIR}/scripts:/scripts"
    environment:
      ACCEPT_EULA: ${MSSQL_ACCEPT_EULA:-Y}
      MSSQL_PID: ${MSSQL_PID:-Developer}
      MSSQL_SA_PASSWORD: ${MSSQL_PASSWORD:-Password4ever}
      MSSQL.master.datafile: /var/opt/mssql/data/master.mdf
      MSSQL.master.logfile: /var/opt/mssql/data/mastlog.ldf
      MSSQL_BACKUP_DIR: /var/opt/mssql/backup
