version: '3.6'

services:

  runner:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runner
    hostname: gitlab-runner
    privileged: true
    volumes:
      - ${RUNNER_DATA_DIR}/etc/gitlab-runner/:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8093:8093