# see https://github.com/getredash/redash.git

x-redash-service: &redash-service
  image: redash/redash:25.1.0
  depends_on:
    - postgres
    - redis
  restart: unless-stopped

x-redash-environment: &redash-environment
  REDASH_HOST: http://localhost:${REDASH_PORT:-5000}
  REDASH_LOG_LEVEL: "INFO"
  REDASH_REDIS_URL: "redis://redis:6379/0"
  REDASH_DATABASE_URL: "postgresql://postgres:${POSTGRES_PASSWORD}@postgres/redash"
  REDASH_RATELIMIT_ENABLED: "false"
  REDASH_MAIL_DEFAULT_SENDER: "redash@example.com"
  REDASH_MAIL_SERVER: mailhog
  REDASH_MAIL_PORT: 1025
  REDASH_ENFORCE_CSRF: "true"
  REDASH_GUNICORN_TIMEOUT: 60
  REDASH_SECRET_KEY: ${REDASH_SECRET_KEY}
  REDASH_COOKIE_SECRET: ${REDASH_COOKIE_SECRET}
  GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}

services:
  redash-server:
    <<: *redash-service
    command: dev_server
    ports:
        - "${REDASH_PORT:-5000}:5000"
        - "5678:5678"
    environment:
      <<: *redash-environment
      PYTHONUNBUFFERED: 0
    depends_on:
      - postgres
      - redis
  redash-scheduler:
      <<: *redash-service
      command: dev_scheduler
      depends_on:
        - redash-server
      environment:
        <<: *redash-environment
  redash-worker:
    <<: *redash-service
    command: dev_worker
    depends_on:
      - redash-server
    environment:
      <<: *redash-environment
      PYTHONUNBUFFERED: 0
