version: '3.1'

services:

  pgadmin:
    image: dpage/pgadmin4:6.3
    ports:
      - "${PGADMIN_LISTEN_PORT:-8080}:80"
    depends_on:
      - postgres
    environment:
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:-admin}
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-admin@example.org}
    volumes:
      - ${PGADMIN_ROOT_DIR}/lib:/var/lib/pgadmin
      - ${PGADMIN_ROOT_DIR}/certs/pgadmin.cert:/certs/server.cert
      - ${PGADMIN_ROOT_DIR}/certs/pgadmin.key:/certs/server.key
      - ${PGADMIN_ROOT_DIR}/pgadmin/servers.json:/pgadmin4/servers.json
