version: '3.6'

services:

  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - "9443:9443"
      - "9080:8000"
    volumes:
      - ${PORTAINER_DATA_DIR}:/data
      - /var/run/docker.sock:/var/run/docker.sock
