# Postgres Vector DB https://hub.docker.com/r/pgvector/pgvector/tags?name=18
services:
  pgvector:
    image: pgvector/pgvector:${PGVECTOR_IMAGE}
    command: -c 'max_connections=${PGVECTOR_MAX_CONNECTIONS:-100}'
    ports:
      - "56${PGVECTOR_VERSION}:5432"
    volumes:
      - "${PGVECTOR_ROOT_DATA_DIR}${PGVECTOR_VERSION}:/var/lib/postgresql"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
