# Postgres Vector DB https://hub.docker.com/r/pgvector/pgvector/tags?name=18
services:
  pgvector-anon:
    build:
      context: ./postgres-pgvector-anon
      args:
        PGV_VECTOR_ANON_IMAGE: ${PGV_ANON_IMAGE}
        PGV_ANON_VERSION: ${PGV_ANON_VERSION}
    image: k-tech.it/pgvector-anon
    command: -c 'max_connections=${PGV_MAX_CONNECTIONS:-100}'
    ports:
      - "56${PGV_ANON_PORT}:5432"
    volumes:
      - "${PGV_ANON_ROOT_DATA_DIR}${PGV_ANON_VERSION}:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
