version: 0.1
log:
  level: debug
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
  delete:
    enabled: true
http:
  addr: :5000
  secret: asecretforlocaldevelopment
  headers:
    Access-Control-Allow-Origin: ['*']
    X-Content-Type-Options: [nosniff]
    Access-Control-Allow-Methods: ['HEAD', 'GET', 'OPTIONS', 'DELETE']
    Access-Control-Expose-Headers: ['Docker-Content-Digest']
    # Access-Control-Allow-Headers: ['Authorization', 'Accept']
    # Access-Control-Max-Age: [1728000]
    # Access-Control-Allow-Credentials: [true]
# auth:
#   silly:
#     realm: silly-realm
#     service: silly-service
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
